name: "SOOS DAST Scan"

on: [push]   

jobs:
  soos:
    name: SOOS DAST Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Analysis
        uses: soos-io/soos-dast-github-action@b3f6fe3668be3cb8f8aeee92e55de2d92038d139
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: "DAST Github Actions Test"
          scan_mode: "baseline"
          target_url: "https://brokencrystals.com/"
          api_url: "https://qa-api.soos.io/api/"
          image_tag: alpha
          verbose: true
